export const ApplicationDispatchAction = {
    SET_AUTHENTICATED: 'SET_AUTHENTICATED',
    SET_FIRST_TIME: 'SET_FIRST_TIME',
    SET_DID: 'SET_DID',
    SET_AUTHENTICATION_PIN: 'SET_AUTHENTICATION_PIN',
};
